// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv15upSqwvDm7hWbzGdNE5XpC3P-71iEo',
    appId: '1:979310102971:web:86db8e63b50cd6f2921c9e',
    messagingSenderId: '979310102971',
    projectId: 'mandaloasinoma-api',
    authDomain: 'mandaloasinoma-api.firebaseapp.com',
    storageBucket: 'mandaloasinoma-api.appspot.com',
    measurementId: 'G-RQX90HNFMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFX-nf_0luXFK0nnEFmTSBeQrGQQHrczE',
    appId: '1:979310102971:android:f344b3e6f49c6993921c9e',
    messagingSenderId: '979310102971',
    projectId: 'mandaloasinoma-api',
    storageBucket: 'mandaloasinoma-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWDt4FBFPHHcrzHrmiW58CcGyJiQxB7Dw',
    appId: '1:979310102971:ios:576e594b2aa2734b921c9e',
    messagingSenderId: '979310102971',
    projectId: 'mandaloasinoma-api',
    storageBucket: 'mandaloasinoma-api.appspot.com',
    iosBundleId: 'com.joyel.mandaloasinomaApp',
  );
}
